sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
jdk:
  - openjdk8
script:
  - mvn -B -T2 -fae clean install
notifications:
  email: false
  on_failure: never
after_success:
 - mvn clean cobertura:cobertura coveralls:report
